### ISSUE TITLE
[Feature Request] Add support for Google Container Registry integration

### ISSUE THREAD

**Issue by miles-** [terraform-providers/terraform-provider-lacework#21]
First of all, thank you for all of the work on this Terraform provider!

Ideally, I'd like to create all Lacework integrations via Terraform. This is possible today for Google Cloud Platform compliance and audit trail integrations, but not for Google Container Registry. [Here](https://support.lacework.com/hc/en-us/articles/360047770014) is the Lacework guide for setting up the GCR integration manually.

I imagine this resource would look similar to the `lacework_integration_gcp_cfg` resource.

**Comment by scottford-lw** [comment]
@miles- Thank you very much for your feedback and for opening this FR. We are in complete agreement with you and have this in our backlog. Our current plan is to provide specific custom resources for each of the registries we support...


```
lacework_integration_gcr
lacework_integration_ecr
lacework_integration_docker_hub
lacework_integration_docker_v2
```

**Comment by afiune** [comment]
Started to work on these features. 

We will consume this work https://github.com/lacework/go-sdk/pull/205

**Comment by afiune** [comment]
@miles- we have completed the development of this feature! 🙌🏽💯⭐ We have requested a new release of our provider with version `v0.2.4`, Hashicorp is pretty fast with these releases we should have it anytime today no later than tomorrow.

Please let us know if there are any question or doubt to implement these new resources, thank you for your feedback!

![tenor-206419191](https://user-images.githubusercontent.com/5712253/92784838-2a4a1a00-f364-11ea-8011-230482b0270d.gif)
